
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "My first bloga",
    "author": "zim",
    "url":"no you are L",
    "likes": 1

}

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "steveblogs",
    "name": "steve",
    "password":"sgolbevets"

}

