
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbGYiLCJpZCI6IjY4NGJhM2U3OWQ4YjdjNzVlYjkyODU2NSIsImlhdCI6MTc1MDk4NTE5MywiZXhwIjoxNzUwOTg4NzkzfQ.ibdV4auvqMEe4K2e1kf6SfGdXPtoYek50x7XTXeCd0s

{
    "title": "My first bloga",
    "url":"no you are L"

}

###
DELETE http://localhost:3003/api/blogs/685deb67709a958ac742f184
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndhbGYiLCJpZCI6IjY4NGJhM2U3OWQ4YjdjNzVlYjkyODU2NSIsImlhdCI6MTc1MDk4NTE5MywiZXhwIjoxNzUwOTg4NzkzfQ.ibdV4auvqMEe4K2e1kf6SfGdXPtoYek50x7XTXeCd0s

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "walf",
    "name": "steve",
    "password":"111"

}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "tim",
    "name": "timo",
    "password":"111"
}


###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "walf",
    "password":"111"

}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "tim",
    "password":"111"

}